---
secretKey: 'imsosecret'
files:
  # - testfiles/config.json
  # - testfiles/coverage_testfile.xml
  # - testfiles/helpers.sh
  - testfiles/id_rsa
  # - testfiles/id_rsa.pub
  # - testfiles/main.go
  # - testfiles/supervisor_env
  # - testfiles/secrets.geheim.yaml
  # - testfiles/simple.txt
