name: golangci-lint
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
