---
name: tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  test_cov:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17.5
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Run tests
        run: make test_all
