---
name: tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  test_all:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17.5
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Run tests
        run: make test_all
      - name: Run benchmarks
        run: make benchmarks
      - name: Prepare coverage
        run: |
          mkdir coverage
          make test_cov
          mv coverage.html coverage
      - name: Publish coverage
        uses: actions/upload-artifact@v2
        with: 
          name: coverage
          path: coverage
